version: '3'

services:

  docker-mysql:
    container_name: docker-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: abc123
    expose:
      - 3306
    ports:
      - 3307:3306
    networks:
      - restaurant-network
    restart: always

  bankaccount-api:
    restart: on-failure
    container_name: restaurant-api
    build:
      context: .
      dockerfile: restaurant-api.dockerfile
    image: restaurant-api:latest
    expose:
      - 8091
    ports:
      - 8091:8091
    networks:
      - restaurant-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/restaurant
    depends_on:
      - docker-mysql

networks:
  restaurant-network:
    driver: bridge